import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import * as fs from "node:fs";

const prodBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// In dev builds, synchronously fetch and eval the React DevTools backend script
// BEFORE React loads, so the hook + WebSocket connection are set up in time.
// Uses Node.js child_process (available in Electron) to bypass CORS.
const devToolsHook = `
(function() {
  try {
    var s = require('child_process').execSync(
      'curl -sf http://localhost:8097',
      { timeout: 2000, encoding: 'utf-8' }
    );
    if (s) (0, eval)(s);
  } catch(e) {}
})();
`;

const prod = process.argv[2] === "production";

const banner = prod ? prodBanner : prodBanner + devToolsHook;

const rebuildPlugin = {
  name: "rebuild-handler",
  setup(build) {
    build.onEnd(async () => {
      await fs.promises.rename("main.css", "styles.css");
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [rebuildPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
